import { iTranslations } from '../EnvironmentInterface'

export const en:iTranslations = {
    "nixin": "NIXIN",
    "global.installApp": "Install NIXINx",
    "global.Accept": "Accept",
    "global.Reject": "Reject",
    "global.Understand": "Ok",
    "global.return": "Return",
    "global.Storage": "Keep my preferences such as country, language.. in this device.",
    "global.Read": "(Read more)",
    "global.Search": "Search...",
    "global.Adjust": "Adjust",
    "global.Duedate": "Expiration",
    "global.Success": "Success!",
    "global.true": "Si",
    "global.false": "No",
    "global.NA": "Not Apply",
    "global.ClosePopUp": "Close",
    "loby.slogan": "Find your Lifestyle, Let's build the future now.",
    "loby.RealEstate": "Real Estate",
    "loby.ServiceEstablishments": "Services & Establishments",
    "loby.REFavorites": "My favorite Properties ",
    "loby.ZSEStickys": "My Stikys ",
    "loby.autocomplete": "Interest Zone",
    "loby.SingIn": "Sign In",
    "loby.SingOut": "Sign Out",
    "loby.Reset": "Reset",
    "footer.terms": "Terms and Conditions",
    "footer.privacy": "Notice of Privacy",
    "footer.blog": "Blog",
    "footer.contact": "Contact",
    "footer.survey": "Survey",
    "footer.tutorials": "Tutorials",
    "footer.prices": "Prices",
    "footer.promoters": "Promoters",
    "header.signout": "Sign Out",
    "header.portal": "My Portal",
    "header.searchbar": "Search Bar",
    "header.signin": "Sign In",
    "header.country": "Country",
    "header.nightmode": "Night",
    "header.filters": "Filters",
    "header.tellme": "Tell me",
    "header.liked": "Liked",
    "header.stickys": "Stickys",
    "header.properties": "RealEstate",
    "header.services": "Services",
    "header.changeLangCntry": "Apply",
    "adscards.contact": "Contact",
    "repopup.usrank": "My rank",
    "repopup.reqinfo": "Request Information",
    "repopup.routemap": "Writte a destiny to know times and distances from this ",
    "repopup.placesmap": "Choose the Type of Places",
    "repopup.new": "New",
    "mktfilters.portalkind": "Portal",
    "mktfilters.clients": "Clients",
    "mktfilters.brokers": "Brokers",
    "mktfilters.developments": "Real Estate Developments",
    "mktfilters.country": "Country",
    "mktfilters.prst": "State",
    "mktfilters.oper": "Transaction",
    "mktfilters.rent": "Rent",
    "mktfilters.sell": "Sell",
    "mktfilters.contract": "Hiring",
    "mktfilters.property": "Property",
    "mktfilters.house": "House",
    "mktfilters.apartment": "Apartment",
    "mktfilters.land": "Land",
    "mktfilters.development": "Development",
    "mktfilters.hollyday": "Vacation",
    "mktfilters.events": "For Events",
    "mktfilters.office": "Office",
    "mktfilters.commerce": "commercial place",
    "mktfilters.storage": "Storage",
    "mktfilters.others": "Others",
    "mktfilters.auctons": "Auctions",
    "mktfilters.include": "Include",
    "mktfilters.exclude": "Exclude",
    "mktfilters.only": "Only",
    "mktfilters.order": "Order",
    "mktfilters.usrank": "My rank",
    "mktfilters.cheapest": "Lowest Price",
    "mktfilters.expensive": "Highest Price",
    "mktfilters.filter": "Filter",
    "mktfilters.bedrooms": "Rooms",
    "mktfilters.bathrooms": "Bathrooms",
    "mktfilters.parks": "Parkings",
    "mktfilters.min": "$Min",
    "mktfilters.max": "$Max",
    "mktfilters.zone": "Del./Mun./Cou.",
    "mktfilters.col": "Colonia",
    "mktfilters.residence": "Residential",
    "mktfilters.enjoy": "Joy",
    "mktfilters.commercial": "Commercial",
    "mktfilters.more": "More",
    "mktfilters.alertme": "Create Alert",
    "adrestatecard.ConceptImgPack": "Image Spaces",
    "adrestatecard.DescrImgPack": "The monthly cost for each additional image space depends on the ad payment model.",
    "adrestatecard.ConceptProdRelevAd": "Highlight Ad",
    "adrestatecard.DescrRelevAd": "By highlighting ads you increase your reputation as a Partner and improve the positioning of all your publications simultaneously, mainly benefiting this publication.",
    "adrestatecard.PPEventDescrREAd": "When a user requests to be contacted, the balance corresponding to the transaction points will be deducted for their release.",
    "adrestatecard.PPUseDescrREAd": "In each display of your ad, visit, bookmarking or contact, the points will be deducted for the corresponding transaction.",
    "adrestatecard.UseMemberSpaceDescrREAd": "Occupy with this publication one of the available spaces of the Membership?",
    "adrestatecard.myREStep": "Real Estate Advertisment",
    "adrestatecard.myREStepAdv": "Property Publication with ID: {CardID}",
    "adrestatecard.success": "Successful Publication of Real Estate with ID: {CardID}",
    "adrestatecard.error": "Publication failed. {error}",
    "adrestatecard.myREStepPPEvent": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adrestatecard.myREStepPPUse": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adrestatecard.myREStepPREPay": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adrestatecard.myREStepPromise": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adrestatecard.myREStepMembership": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adrestatecard.InvalidFileLogo": " Rejected. Valid formats for images are: png, jpg, jpeg, gif, webp",
    "adrestatecard.InvalidFilePreview": " Rejected. Valid formats for images are: png, jpg, jpeg, gif, webp",
    "adrestatecard.msjgoodpractices": "Adjust your descriptions to be able to publish in the 'Pay Per Event' model since your publication contains {SocialMed} {Numbers} in the description and you can only add {AcceptedNum} figures. Readjust your descriptions and avoid repeating data already added to the characteristics of the property such as parking spaces, etc ... or you can choose another payment model without this restriction.",
    "adrestatecard.titlegoodpractices": "Good Practices Check Up",
    "adrestatecard.tutgoodpractitle": "Avoid contact details",
    "adrestatecard.signnewad": "Sign Terms and Conditions",
    "adrestatecard.signnewdescr": "Password for acceptance of Terms and Conditions invalid",
    "adrestatecard.sucovrpct": "Successful upload with {cargadas} loaded images from the {previsualizadas} posted due to duplication or oversize. Applicable charges consider only uploaded images. We will send you the details of your ad by email once it has been verified compliance with good practices prior to publication.",
    "adrestatecard.sucovrpctppevent": "Successful upload. We will send you a detailed email once compliance with good practices has been verified before publication.",
    "adrestatecard.sucovrpctppuse": "Successful upload. We will send you a detailed email. Remember to have available points in your balance prior to its publication and for subsequent applicable charges.",
    "adrestatecard.sucovrpctmembersh": "Successful upload. we will send you a detailed email to keep your publication scrollable.",
    "adrestatecard.adconcluded": "Announcement Concluded",
    "adrestatecard.pmtmodbenef": "My payement model and benefits",
    "adrestatecard.titlogo": "Your real estate logotype (optional). Not visible in the 'Pay per Event' model",
    "adrestatecard.logo": "Attach your Logo for this ad.",
    "adrestatecard.freeimg1": "{imgratis} Space (s) for free images.",
    "adrestatecard.freeimg2": " Pictures: (Free) {imgratis}, (Paid) {imgpago}.",
    "adrestatecard.paymentimages": "More spaces for more Images of payment.",
    "adrestatecard.HighlitedAd": "Featured post!",
    "adrestatecard.Higlight": "¡Highlight Ad and Improve Reputation!",
    "adrestatecard.Proptype": "Property type",
    "adrestatecard.Residential": "Residential",
    "adrestatecard.HOME": "House",
    "adrestatecard.APARTMENT": "Apartment",
    "adrestatecard.DEVELOPMENT": "Real state development",
    "adrestatecard.PRESELL": "Presale",
    "adrestatecard.LAND": "Land",
    "adrestatecard.ROOM": "Room",
    "adrestatecard.PROJECT": "Architectural project",
    "adrestatecard.Rest": "Vacation",
    "adrestatecard.RESTHOME": "House",
    "adrestatecard.RESTAPARTMENT": "Apartment",
    "adrestatecard.RESTROOM": "Room",
    "adrestatecard.RESTOTHER": "Other",
    "adrestatecard.Events": "Social Events",
    "adrestatecard.EVENTGARDEN": "Garden",
    "adrestatecard.EVENTROOM": "Party room",
    "adrestatecard.EVENTENCLOSURE": "Enclosure",
    "adrestatecard.EVENTOTHER": "Others",
    "adrestatecard.Commerce": "Commercial",
    "adrestatecard.COMLOCAL": "Commercial room",
    "adrestatecard.COMCONSULTING": "Medical room",
    "adrestatecard.COMVIRTUALOFFICE": "Virtual Office",
    "adrestatecard.COMOFFICE": "Office",
    "adrestatecard.COMBUILDING": "Building",
    "adrestatecard.COMFLOOR": "Floor",
    "adrestatecard.COMSTORAGE": "Storage",
    "adrestatecard.COMSTATION": "Market Stall",
    "adrestatecard.COMOTHERCOMERCE": "Other",
    "adrestatecard.Industry": "Industrial",
    "adrestatecard.INDWHAREHOUSE": "Industrial ship",
    "adrestatecard.INDSTORAGE": "Storage",
    "adrestatecard.INDLAND": "Land",
    "adrestatecard.INDOTHER": "Other",
    "adrestatecard.Transtype": "Transaction type",
    "adrestatecard.selltrans": "Sell",
    "adrestatecard.renttrans": "Rent",
    "adrestatecard.passtrans": "Transfer",
    "adrestatecard.Transprice": "Price",
    "adrestatecard.Transaddexp": "Aditional Expenditures?",
    "adrestatecard.NO": "No",
    "adrestatecard.MANTENANCE": "Manteinance",
    "adrestatecard.GUARANTEE": "Legal Policy",
    "adrestatecard.DEPOSIT": "Deposits in guarantee",
    "adrestatecard.RESERVED": "pulled apart",
    "adrestatecard.MULTIPLE": "Multiple",
    "adrestatecard.OTHERS": "Others",
    "adrestatecard.addexpammt": "Aditional Expenditure Ammount",
    "adrestatecard.auction": "Is it a foreclosure?",
    "adrestatecard.feeammount": "Commission Amount or Percentage",
    "adrestatecard.m2c": "Meters built",
    "adrestatecard.m2t": "Land Meters",
    "adrestatecard.m2g": "Garden meters",
    "adrestatecard.bedrooms": "Rooms/Offices/etc.",
    "adrestatecard.bathrooms": "Bathrooms",
    "adrestatecard.parks": "Parking lots",
    "adrestatecard.pets": "Pet Friendly?",
    "adrestatecard.usrkind": "What type of user are you?",
    "adrestatecard.OWNER": "Owner",
    "adrestatecard.BROKER": "Real Estate Agent",
    "adrestatecard.sharefee": "Do you give or share a commission?",
    "adrestatecard.FEENOT": "No",
    "adrestatecard.FEEAMMOUNT": "Monetary Commission $",
    "adrestatecard.FEEPERCENTAGE": "Percentage Commission%",
    "adrestatecard.PETLIMITED": "Limited",
    "adrestatecard.PETCONDITIONS": "Conditioned",
    "adrestatecard.URLvideo": "Property Video Link (URL)",
    "adrestatecard.description": "Description of the Property (Avoid contact information for Payment per Event model)",
    "adrestatecard.condition": "Special Conditions (Avoid contact information for Payment per Event model)",
    "adrestatecard.relevant": "Relevant Aspects (Avoid contact information for Payment per Event model)",
    "adrestatecard.pptyaddrs": "Capture and confirm the address",
    "adrestatecard.prst": "State / Province",
    "adrestatecard.zone": "Delegation / Municipality / Mayor's Office / ...",
    "adrestatecard.col": "Suburb",
    "adrestatecard.street": "Street",
    "adrestatecard.enum": "External and internal number",
    "adrestatecard.zipcode": "Postal Code",
    "adrestatecard.latlong": "Latitud and Longitud from google maps",
    "adrestatecard.gearth": "Google Earth Link URL",
    "adrestatecard.rates": " Current rates for publications in {Cntry}",
    "adrestatecard.buypointsequiv": "Acquire Points (1Pt = {PricePerPoint})",
    "adrestatecard.pmmtmodchosen": "Choose the payment model you prefer for this ad",
    "adrestatecard.ppe1": "Pay per Event",
    "adrestatecard.ppe2": "Free until the moment of contact {PPECntcPrice}.",
    "adrestatecard.ppu1": "Pay per Use",
    "adrestatecard.ppu2": "From {PPUDispPrice} Cents to {PPUCntcPrice} for each share and with a bonus to start without spending.",
    "adrestatecard.memb1": "Membership Use",
    "adrestatecard.memb2": "(Your pre-contracted spaces available)",
    "adrestatecard.membprep1": "Memberships",
    "adrestatecard.membprep2": "Prepaid",
    "adrestatecard.membprep3": "Discounts up to {MaxPrcDiscount} ({MaxAmtDiscount})",
    "adrestatecard.membprom1": "MembreMembershipssías",
    "adrestatecard.membprom2": "Payment promise",
    "adrestatecard.membprom3": "Level 1 to 3 from 2 to 12 months with discounts, benefits and Monthly Payment.",
    "adrestatecard.inputpassword": "Enter your Password",
    "adrestatecard.terms2": "Terms and Conditions",
    "adrestatecard.termsaccept": "Acceptance of current terms to publish",
    "adrestatecard.sendtocheck": "Submit Advertisment for Verification",
    "adrestatecard.sendtopublish": "Submit Advertisment",
    "adrestatecard.buypoints": "Points Acquisition",
    "adzsecard.ConceptImgPack": "Image Spaces",
    "adzsecard.DescrImgPack": "The monthly cost for each additional image space depends on the ad payment model.",
    "adzsecard.ConceptProdRelevAd": "Highlight Ad",
    "adzsecard.DescrRelevAd": "By highlighting ads you increase your reputation as a Partner and improve the positioning of all your publications simultaneously, mainly benefiting this publication.",
    "adzsecard.PPUseDescrREAd": "In each display of your ad, visit, bookmarking or contact, the points will be deducted for the corresponding transaction.",
    "adzsecard.UseMemberSpaceDescrREAd": "Occupy with this publication one of the available spaces of the Membership?",
    "adzsecard.myZSEStep": "Establishment or Service Advertisment",
    "adzsecard.myZSEStepAdv": "Establishment or Service Publication with ID: {CardID}",
    "adzsecard.success": "Successful Publication of Establishment or Service with ID: {CardID}",
    "adzsecard.error": "Publication failed. {error}",
    "adzsecard.myREStepPPUse": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adzsecard.myREStepPREPay": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adzsecard.myREStepPromise": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adzsecard.myREStepMembership": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adzsecard.InvalidFileLogo": " Rejected. Valid formats for images are: png, jpg, jpeg, gif, webp",
    "adzsecard.InvalidFilePreview": " Rejected. Valid formats for images are: png, jpg, jpeg, gif, webp",
    "adzsecard.signnewad": "Sign Terms and Conditions",
    "adzsecard.signnewdescr": "Password for acceptance of Terms and Conditions invalid",
    "adzsecard.sucovrpct": "Successful upload with {cargadas} loaded images from the {previsualizadas} posted due to duplication or oversize. Applicable charges consider only uploaded images. We will send you the details of your ad by email once it has been verified compliance with good practices prior to publication.",
    "adzsecard.sucovrpctppuse": "Successful upload. We will send you a detailed email. Remember to have available points in your balance prior to its publication and for subsequent applicable charges.",
    "adzsecard.sucovrpctmembersh": "Successful upload. we will send you a detailed email to keep your publication scrollable.",
    "adzsecard.adconcluded": "Announcement Concluded",
    "adzsecard.pmtmodbenef": "My payement model and benefits",
    "adzsecard.titlogo": "Logo of your establishment or service (optional). Not visible in the 'Pay per Event' model",
    "adzsecard.logo": "Attach your Logo for this ad.",
    "adzsecard.freeimg1": "{imgratis} Space (s) for free images.",
    "adzsecard.freeimg2": " Pictures: (Free) {imgratis}, (Paid) {imgpago}.",
    "adzsecard.paymentimages": "More spaces for more Images of payment.",
    "adzsecard.HighlitedAd": "Featured post!",
    "adzsecard.Higlight": "¡Highlight Ad and Improve Reputation!",
    "adzsecard.description": "Description of your service or establishment (Avoid contact information in Pay-Per-Event publications)",
    "adzsecard.pptyaddrs": "Capture and confirm the address (optional)",
    "adzsecard.prst": "State / Province",
    "adzsecard.zone": "Delegation / Municipality / Mayor's Office / ...",
    "adzsecard.col": "Suburb",
    "adzsecard.street": "Street",
    "adzsecard.enum": "External and internal number",
    "adzsecard.zipcode": "Postal Code",
    "adzsecard.latlong": "Latitud and Longitud from google maps",
    "adzsecard.gearth": "Google Earth Link URL",
    "adzsecard.rates": " Current rates for publications in {Cntry}",
    "adzsecard.buypointsequiv": "Acquire Points (1Pt = {PricePerPoint})",
    "adzsecard.pmmtmodchosen": "Choose the payment model you prefer for this ad",
    "adzsecard.ppu1": "Pay per Use",
    "adzsecard.ppu2": "From {PPUDispPrice} Cents to {PPUCntcPrice} for each share and with a bonus to start without spending.",
    "adzsecard.memb1": "Membership Use",
    "adzsecard.memb2": "(Your pre-contracted spaces available)",
    "adzsecard.membprep1": "Memberships",
    "adzsecard.membprep2": "Prepaid",
    "adzsecard.membprep3": "Discounts up to {MaxPrcDiscount} ({MaxAmtDiscount})",
    "adzsecard.membprom1": "MembreMembershipssías",
    "adzsecard.membprom2": "Payment promise",
    "adzsecard.membprom3": "Level 1 to 3 from 2 to 12 months with discounts, benefits and Monthly Payment.",
    "adzsecard.inputpassword": "Enter your Password",
    "adzsecard.terms2": "Terms and Conditions",
    "adzsecard.termsaccept": "Acceptance of current terms to publish",
    "adzsecard.sendtocheck": "Submit Advertisment for Verification",
    "adzsecard.sendtopublish": "Submit Advertisment",
    "adzsecard.buypoints": "Points Acquisition",
    "adzsecard.promestablishment": "Promote establishment",
    "adzsecard.promservice": "Offer a Service",
    "adzsecard.category": "Category",
    "adzsecard.HOMEMANTENANCE": "Maintenance (Plumbers, Electrician, Fumigation ...)",
    "adzsecard.HOMESERVICES": "Services (Gas, Garden, Bath / Pet Walk, Cleaning ...)",
    "adzsecard.HOMEOTHER": "Others",
    "adzsecard.ARTHOME": "For home",
    "adzsecard.ARTCAR": "Automotive",
    "adzsecard.ARTOFF": "For Office",
    "adzsecard.ARTPERS": "Personal",
    "adzsecard.ARTDRESS": "Clothing",
    "adzsecard.ARTPET": "For Pets",
    "adzsecard.ARTSCHO": "Academics",
    "adzsecard.ARTOTHER": "Various",
    "adzsecard.HEALTHMEDICINE": "Doctor",
    "adzsecard.HEALTHMENTAL": "Holistic",
    "adzsecard.HEALTHSPORT": "Sports and disciplines",
    "adzsecard.HEALTHFOOD": "Nutritional",
    "adzsecard.HEALTHESTATIC": "Aesthetic",
    "adzsecard.HEALTHPET": "Animal",
    "adzsecard.HEALTHOTHER": "Various",
    "adzsecard.ACADEMICSCHOOL": "School",
    "adzsecard.ACADEMICHELP": "Regularization",
    "adzsecard.ACADEMICEXTRA": "Extracurricular",
    "adzsecard.ACADEMICSPORTS": "Sports and disciplines",
    "adzsecard.ACADEMICSPRING": "Workshops",
    "adzsecard.ACADEMICARTS": "Arts",
    "adzsecard.ACADEMICOTHERS": "Others",
    "adzsecard.PROFESIONALSHEALTH": "For health",
    "adzsecard.PROFESIONALSPSYCHOLOGY": "Psychological",
    "adzsecard.PROFESIONALSLEGAL": "Legal",
    "adzsecard.PROFESIONALSFINANCIAL": "Financial sector",
    "adzsecard.PROFESIONALSCONSULTANT": "Consultants",
    "adzsecard.PROFESIONALSOTHERS": "Others",
    "adzsecard.ENTDIGITAL": "Digital",
    "adzsecard.ENTMUSICAL": "Musical",
    "adzsecard.ENTVISUAL": "Visual",
    "adzsecard.ENTSPORT": "Sporty",
    "adzsecard.ENTSHOW": "Shows",
    "adzsecard.ENTFAMILY": "Family",
    "adzsecard.ENTCULTURE": "Cultural",
    "adzsecard.ENTSOCIAL": "Social Coexistence",
    "adzsecard.ENTOTHERS": "Others",
    "adzsecard.CARMANTENANCE": "Maintenance",
    "adzsecard.CARCOMMERCE": "Commerce",
    "adzsecard.CAROTHERS": "Others",
    "adzsecard.OTHERS": "Various",
    "adzsecard.home": "Home",
    "adzsecard.articles": "Articles",
    "adzsecard.health": "Health & Wellness",
    "adzsecard.academics": "Academics",
    "adzsecard.professional": "Professionals",
    "adzsecard.entretainment": "Entertainment",
    "adzsecard.auto": "Automotive",
    "adzsecard.others": "Others",
    "adzsecard.brand": "Brand Name",
    "adzsecard.keywords": "Search keywords: (Sushi, Plumber, Gas, Stationery, Carpenter, Office, etc.)",
    "adzsecard.slogan": "Slogan",
    "adzsecard.homeservice": "Do you offer Home Service?",
    "adzsecard.website": "Internet page",
    "adzsecard.email": "Email",
    "adzsecard.tel1": "Telephone 1",
    "adzsecard.tel2": "Telephone 2",
    "adzsecard.tel3": "Telephone 3",
    "adzsecard.whatsapp": "WhatsApp",
    "adzsecard.wechat": "WeChat",
    "adzsecard.facebook": "facebook",
    "adzsecard.instagram": "Instagram",
    "adzsecard.twiter": "Twiter",
    "adzsecard.youtube": "Youtube",
    "adzsecard.appstore": "Link to your IOs AppStore",
    "adzsecard.playstore": "Link to your Google Play store",
    "adzsecard.color": "Background Color of your ad",
    "adzsecard.videourl": "Video link (URL) of your establishment or service",
    "adzsecard.promotions": "Promotions",
    "adzsecard.calltoact": "Call to Action",
    "adzsecard.branches": "Branches",
    "adzsecard.schedule": "Opening times",
    "adzsecard.day1": "Monday",
    "adzsecard.day2": "Tuesday",
    "adzsecard.day3": "Wednesday",
    "adzsecard.day4": "Thursday",
    "adzsecard.day5": "Friday",
    "adzsecard.day6": "Saturday",
    "adzsecard.day7": "Sunday",
    "adzsecard.from": "From: ",
    "adzsecard.to": "To: ",
    "adzsecard.important": "IMPORTANT:",
    "adzsecard.zonestopublish": "In which areas will you publish your ad? ({zonas} posts)",
    "adzsecard.advise": "Each Zone counts as 1 more ad on your account statement",
    "adzsecard.autocompletezones": "Write here the areas where you will publish your ad",
    "adzsecard.typecharpublish": "Choose the type and characteristics of your Publication.",
    "adzsecard.frontcard": "Front Card ({PtsReq} pts)",
    "adzsecard.backcard": "Front and Back Card ({PtsReq} pts)",
    "adzsecard.fullcard": "Front Card and Full Screen ({PtsReq} pts)",
    "adzsecard.addoptfrontcard": "Additional Front Card Options",
    "adzsecard.titlogocard": "Add your Logo",
    "adzsecard.logocard": "Logo ( {PtsReq} pts)",
    "adzsecard.tithomeservicecard": "Enable Home Service Icon",
    "adzsecard.homeservicecard": "Home Service ({PtsReq} pts)",
    "adzsecard.titactivenotificationcard": "Notify your Promotions to any user of the Services portal",
    "adzsecard.activenotificationcard": "Active Notification ({PtsReq} pts)",
    "adzsecard.titpassivenotificationcard": "Notify your promotions to whoever marks you with Sticky",
    "adzsecard.passivenotificationcard": "Passive Notifications ({PtsReq} pts)",
    "adzsecard.titsharebymailwhatscard": "Enable that they can share you by Mail and WhatsApp",
    "adzsecard.sharebymailwhatscard": "Share by messaging ({PtsReq} pts)",
    "adzsecard.titchatfollowcard": "Receive requests for quotes or doubts from the portal",
    "adzsecard.chatfollowcard": "Written Contact ({PtsReq} pts)",
    "adzsecard.titsmsnotifcard": "Receive SMS Notifications when a customer requests Information",
    "adzsecard.smsnotifcard": "Active SMS ({PtsReq} pts)",
    "adzsecard.titmyzoneblogcard": "Appears on dynamic cards on the main services screen",
    "adzsecard.myzoneblogcard": "Signs in the Service Portal ({PtsReq} pts)",
    "adzsecard.titpublicblogcard": "Appears in dynamic cards on the portal blog",
    "adzsecard.publicblogcard": "Labels in Blog ({PtsReq} pts)",
    "adzsecard.addoptbackcard": "Additional Back Card Options",
    "adzsecard.titschedulecard": "Report your hours of operation",
    "adzsecard.schedulecard": "Hours ({PtsReq} pts)",
    "adzsecard.titshowsocialmedcard": "Enable Icons that connect with your social networks",
    "adzsecard.showsocialmedcard": "Show Social Networks ({PtsReq} pts)",
    "adzsecard.titpricelistcard": "Add your price list",
    "adzsecard.pricelistcard": "Price List ({PtsReq} pts)",
    "adzsecard.titproductscard": "Add a catalog of 7 products with description and / or price",
    "adzsecard.productscard": "Product Catalog ({PtsReq} pts)",
    "adzsecard.titdescriptionscard": "Describe all products",
    "adzsecard.descriptionscard": "Descriptions ({PtsReq} pts)",
    "adzsecard.titcalltoactcard": "Invite your Interested Parties to take an action",
    "adzsecard.calltoactcard": "Call to Action ({PtsReq} pts)",
    "adzsecard.titgoogleappstorescard": "IOs App Store and / or Google Playstore",
    "adzsecard.googleappstorescard": "Digital Stores ({PtsReq} pts)",
    "adzsecard.addoptfullcard": "Additional Options for Full Screen",
    "adzsecard.titgeolocatecard": "Appears on portal maps",
    "adzsecard.geolocatecard": "Geolocation ({PtsReq} pts)",
    "adzsecard.titbranchesmapcard": "Add a hyperlink to your branch map",
    "adzsecard.branchesmapcard": "Branch Map ({PtsReq} pts)",
    "adzsecard.titvideocard": "Add videos to your ad from our youtube channel",
    "adzsecard.videocard": "Videos from NIXIN Channel ({PtsReq} pts)",
    "adzsecard.titqucodecard": "Add a QR code",
    "adzsecard.qucodecard": "QR code ({PtsReq} pts)",
    "adncacard.ConceptImgPack": "Image Spaces",
    "adncacard.DescrImgPack": "The monthly cost for each additional image space depends on the ad payment model.",
    "adncacard.ConceptProdRelevAd": "Highlight Ad",
    "adncacard.DescrRelevAd": "By highlighting ads you increase your reputation as a Partner and improve the positioning of all your publications simultaneously, mainly benefiting this publication.",
    "adncacard.PPUseDescrREAd": "In each display of your ad, visit, bookmarking or contact, the points will be deducted for the corresponding transaction.",
    "adncacard.UseMemberSpaceDescrREAd": "Occupy with this publication one of the available spaces of the Membership?",
    "adncacard.myNCAStep": "Publication addressed to NIXIN Advertisers",
    "adncacard.myNCAStepAdv": "NIXIN Advertiser Post ID: {CardID}",
    "adncacard.success": "Successful Publishing for NIXIN Advertisers with ID: {CardID}",
    "adncacard.error": "Publication failed. {error}",
    "adncacard.myNCAStepPPUse": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adncacard.myNCAStepPREPay": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adncacard.myNCAStepPromise": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adncacard.myNCAStepMembership": "Sign with your password the Acceptance of the terms and conditions for its verification and Publication",
    "adncacard.InvalidFileLogo": " Rejected. Valid formats for images are: png, jpg, jpeg, gif, webp",
    "adncacard.InvalidFilePreview": " Rejected. Valid formats for images are: png, jpg, jpeg, gif, webp",
    "adncacard.signnewad": "Sign Terms and Conditions",
    "adncacard.signnewdescr": "Password for acceptance of Terms and Conditions invalid",
    "adncacard.sucovrpct": "Successful upload with {cargadas} loaded images from the {previsualizadas} posted due to duplication or oversize. Applicable charges consider only uploaded images. We will send you the details of your ad by email once it has been verified compliance with good practices prior to publication.",
    "adncacard.sucovrpctppuse": "Successful upload. We will send you a detailed email. Remember to have available points in your balance prior to its publication and for subsequent applicable charges.",
    "adncacard.sucovrpctmembersh": "Successful upload. we will send you a detailed email to keep your publication scrollable.",
    "adncacard.adconcluded": "Announcement Concluded",
    "adncacard.pmtmodbenef": "My payement model and benefits",
    "adncacard.titlogo": "Logo of your establishment or service (optional). Not visible in the 'Pay per Event' model",
    "adncacard.logo": "Attach your Logo for this ad.",
    "adncacard.freeimg1": "{imgratis} Space (s) for free images.",
    "adncacard.freeimg2": " Pictures: (Free) {imgratis}, (Paid) {imgpago}.",
    "adncacard.paymentimages": "More spaces for more Images of payment.",
    "adncacard.HighlitedAd": "Featured post!",
    "adncacard.Higlight": "¡Highlight Ad and Improve Reputation!",
    "adncacard.description": "Description of your establishment or service (Avoid contact information in Pay-Per-Event publications)",
    "adncacard.pptyaddrs": "Capture and confirm the address (optional)",
    "adncacard.prst": "State / Province",
    "adncacard.zone": "Delegation / Municipality / Mayor's Office / ...",
    "adncacard.col": "Suburb",
    "adncacard.street": "Street",
    "adncacard.enum": "External and internal number",
    "adncacard.zipcode": "Postal Code",
    "adncacard.latlong": "Latitud and Longitud from google maps",
    "adncacard.gearth": "Google Earth Link URL",
    "adncacard.rates": " Current rates for publications in {Cntry}",
    "adncacard.buypointsequiv": "Acquire Points (1Pt = {PricePerPoint})",
    "adncacard.pmmtmodchosen": "Choose the payment model you prefer for this ad",
    "adncacard.ppu1": "Pay per Use",
    "adncacard.ppu2": "From {PPUDispPrice} Cents to {PPUCntcPrice} for each share and with a bonus to start without spending.",
    "adncacard.memb1": "Membership Use",
    "adncacard.memb2": "(Your pre-contracted spaces available)",
    "adncacard.membprep1": "Memberships",
    "adncacard.membprep2": "Prepaid",
    "adncacard.membprep3": "Discounts up to {MaxPrcDiscount} ({MaxAmtDiscount})",
    "adncacard.membprom1": "MembreMembershipssías",
    "adncacard.membprom2": "Payment promise",
    "adncacard.membprom3": "Level 1 to 3 from 2 to 12 months with discounts, benefits and Monthly Payment.",
    "adncacard.inputpassword": "Enter your Password",
    "adncacard.terms2": "Terms and Conditions",
    "adncacard.termsaccept": "Acceptance of current terms to publish",
    "adncacard.sendtocheck": "Submit Advertisment for Verification",
    "adncacard.sendtopublish": "Submit Advertisment",
    "adncacard.buypoints": "Points Acquisition",
    "adncacard.promestablishment": "Promote establishment",
    "adncacard.promservice": "Offer a Service",
    "adncacard.category": "Category",
    "adncacard.HOMEMANTENANCE": "Maintenance (Plumbers, Electrician, Fumigation ...)",
    "adncacard.HOMESERVICES": "Services (Gas, Garden, Bath / Pet Walk, Cleaning ...)",
    "adncacard.HOMEOTHER": "Others",
    "adncacard.ARTHOME": "For home",
    "adncacard.ARTCAR": "Automotive",
    "adncacard.ARTOFF": "For Office",
    "adncacard.ARTPERS": "Personal",
    "adncacard.ARTDRESS": "Clothing",
    "adncacard.ARTPET": "For Pets",
    "adncacard.ARTSCHO": "Academics",
    "adncacard.ARTOTHER": "Various",
    "adncacard.HEALTHMEDICINE": "Doctor",
    "adncacard.HEALTHMENTAL": "Holistic",
    "adncacard.HEALTHSPORT": "Sports and disciplines",
    "adncacard.HEALTHFOOD": "Nutritional",
    "adncacard.HEALTHESTATIC": "Aesthetic",
    "adncacard.HEALTHPET": "Animal",
    "adncacard.HEALTHOTHER": "Various",
    "adncacard.ACADEMICSCHOOL": "School",
    "adncacard.ACADEMICHELP": "Regularization",
    "adncacard.ACADEMICEXTRA": "Extracurricular",
    "adncacard.ACADEMICSPORTS": "Sports and disciplines",
    "adncacard.ACADEMICSPRING": "Workshops",
    "adncacard.ACADEMICARTS": "Arts",
    "adncacard.ACADEMICOTHERS": "Others",
    "adncacard.PROFESIONALSHEALTH": "For health",
    "adncacard.PROFESIONALSPSYCHOLOGY": "Psychological",
    "adncacard.PROFESIONALSLEGAL": "Legal",
    "adncacard.PROFESIONALSFINANCIAL": "Financial sector",
    "adncacard.PROFESIONALSCONSULTANT": "Consultants",
    "adncacard.PROFESIONALSOTHERS": "Others",
    "adncacard.ENTDIGITAL": "Digital",
    "adncacard.ENTMUSICAL": "Musical",
    "adncacard.ENTVISUAL": "Visual",
    "adncacard.ENTSPORT": "Sporty",
    "adncacard.ENTSHOW": "Shows",
    "adncacard.ENTFAMILY": "Family",
    "adncacard.ENTCULTURE": "Cultural",
    "adncacard.ENTSOCIAL": "Social Coexistence",
    "adncacard.ENTOTHERS": "Others",
    "adncacard.CARMANTENANCE": "Maintenance",
    "adncacard.CARCOMMERCE": "Commerce",
    "adncacard.CAROTHERS": "Others",
    "adncacard.OTHERS": "Various",
    "adncacard.home": "Home",
    "adncacard.articles": "Articles",
    "adncacard.health": "Health & Wellness",
    "adncacard.academics": "Academics",
    "adncacard.professional": "Professionals",
    "adncacard.entretainment": "Entertainment",
    "adncacard.auto": "Automotive",
    "adncacard.others": "Others",
    "adncacard.brand": "Brand Name",
    "adncacard.keywords": "Search keywords: (Sushi, Plumber, Gas, Stationery, Carpenter, Office, etc.)",
    "adncacard.slogan": "Slogan",
    "adncacard.homeservice": "Do you offer Home Service?",
    "adncacard.website": "Internet page",
    "adncacard.email": "Email",
    "adncacard.tel1": "Telephone 1",
    "adncacard.tel2": "Telephone 2",
    "adncacard.tel3": "Telephone 3",
    "adncacard.whatsapp": "WhatsApp",
    "adncacard.wechat": "WeChat",
    "adncacard.facebook": "facebook",
    "adncacard.instagram": "Instagram",
    "adncacard.twiter": "Twiter",
    "adncacard.youtube": "Youtube",
    "adncacard.appstore": "Link to your IOs AppStore",
    "adncacard.playstore": "Link to your Google Play store",
    "adncacard.color": "Background Color of your ad",
    "adncacard.videourl": "Establishment or Service Video link (URL)",
    "adncacard.promotions": "Promotions",
    "adncacard.calltoact": "Call to Action",
    "adncacard.branches": "Branches",
    "adncacard.schedule": "Opening times",
    "adncacard.day1": "Monday",
    "adncacard.day2": "Tuesday",
    "adncacard.day3": "Wednesday",
    "adncacard.day4": "Thursday",
    "adncacard.day5": "Friday",
    "adncacard.day6": "Saturday",
    "adncacard.day7": "Sunday",
    "adncacard.from": "From: ",
    "adncacard.to": "To: ",
    "adncacard.important": "IMPORTANT:",
    "adncacard.zonestopublish": "In which areas will you publish your ad? ({zonas} posts)",
    "adncacard.advise": "Each Zone counts as 1 more ad on your account statement",
    "adncacard.autocompletezones": "Write here the areas where you will publish your ad",
    "adncacard.typecharpublish": "Choose the type and characteristics of your Publication.",
    "adncacard.frontcard": "Front Card ({PtsReq} pts)",
    "adncacard.backcard": "Front and Back Card ({PtsReq} pts)",
    "adncacard.fullcard": "Front Card and Full Screen ({PtsReq} pts)",
    "adncacard.addoptfrontcard": "Additional Front Card Options",
    "adncacard.titlogocard": "Add your Logo",
    "adncacard.logocard": "Logo ( {PtsReq} pts)",
    "adncacard.tithomeservicecard": "Enable Home Service Icon",
    "adncacard.homeservicecard": "Home Service ({PtsReq} pts)",
    "adncacard.titactivenotificationcard": "Notify your Promotions to any user of the Services portal",
    "adncacard.activenotificationcard": "Active Notification ({PtsReq} pts)",
    "adncacard.titpassivenotificationcard": "Notify your promotions to whoever marks you with Sticky",
    "adncacard.passivenotificationcard": "Passive Notifications ({PtsReq} pts)",
    "adncacard.titsharebymailwhatscard": "Enable that they can share you by Mail and WhatsApp",
    "adncacard.sharebymailwhatscard": "Share by messaging ({PtsReq} pts)",
    "adncacard.titchatfollowcard": "Receive requests for quotes or doubts from the portal",
    "adncacard.chatfollowcard": "Written Contact ({PtsReq} pts)",
    "adncacard.titsmsnotifcard": "Receive SMS Notifications when a customer requests Information",
    "adncacard.smsnotifcard": "Active SMS ({PtsReq} pts)",
    "adncacard.titmyzoneblogcard": "Appears on dynamic cards on the main services screen",
    "adncacard.myzoneblogcard": "Signs in the Service Portal ({PtsReq} pts)",
    "adncacard.titpublicblogcard": "Appears in dynamic cards on the portal blog",
    "adncacard.publicblogcard": "Labels in Blog ({PtsReq} pts)",
    "adncacard.addoptbackcard": "Additional Back Card Options",
    "adncacard.titschedulecard": "Report your hours of operation",
    "adncacard.schedulecard": "Hours ({PtsReq} pts)",
    "adncacard.titshowsocialmedcard": "Enable Icons that connect with your social networks",
    "adncacard.showsocialmedcard": "Show Social Networks ({PtsReq} pts)",
    "adncacard.titpricelistcard": "Add your price list",
    "adncacard.pricelistcard": "Price List ({PtsReq} pts)",
    "adncacard.titproductscard": "Add a catalog of 7 products with description and / or price",
    "adncacard.productscard": "Product Catalog ({PtsReq} pts)",
    "adncacard.titdescriptionscard": "Describe all products",
    "adncacard.descriptionscard": "Descriptions ({PtsReq} pts)",
    "adncacard.titcalltoactcard": "Invite your Interested Parties to take an action",
    "adncacard.calltoactcard": "Call to Action ({PtsReq} pts)",
    "adncacard.titgoogleappstorescard": "IOs App Store and / or Google Playstore",
    "adncacard.googleappstorescard": "Digital Stores ({PtsReq} pts)",
    "adncacard.addoptfullcard": "Additional Options for Full Screen",
    "adncacard.titgeolocatecard": "Appears on portal maps",
    "adncacard.geolocatecard": "Geolocation ({PtsReq} pts)",
    "adncacard.titbranchesmapcard": "Add a hyperlink to your branch map",
    "adncacard.branchesmapcard": "Branch Map ({PtsReq} pts)",
    "adncacard.titvideocard": "Add videos to your ad from our youtube channel",
    "adncacard.videocard": "Videos from NIXIN Channel ({PtsReq} pts)",
    "adncacard.titqucodecard": "Add a QR code",
    "adncacard.qucodecard": "QR code ({PtsReq} pts)",
    "adtoblogcard.pubinblog": "Post to the NIXIN Blog"
}