import { iTranslations } from '../EnvironmentInterface'

export const fr:iTranslations = {
    "nixin": "NIXIN",
    "global.installApp": "Installer NIXINx",
    "global.Accept": "Accepter",
    "global.Reject": "Rejeter",
    "global.Understand": "Entendu",
    "global.return": "Rendre",
    "global.Storage": "Enregistrez mes préférences de navigation comme pays, langue.. dans cet appareil.",
    "global.Read": "(Lire plus)",
    "global.Search": "Chercher...",
    "global.Adjust": "Régler",
    "global.Duedate": "Expiration",
    "global.Success": "Succès!",
    "global.true": "Oui",
    "global.false": "No",
    "global.NA": "Ne s'applique pas",
    "global.ClosePopUp": "Fermer",
    "loby.slogan": "Trouvez votre style de vie, Construisons l'avenir maintenant.",
    "loby.RealEstate": "Biens Immobiliers",
    "loby.ServiceEstablishments": "Commerces et Services",
    "loby.REFavorites": "Mes propriétés choisies ",
    "loby.ZSEStickys": "Mes Stiky ",
    "loby.autocomplete": "Zone d'intérêt",
    "loby.SingIn": "S'identifier",
    "loby.SingOut": "Se déconnecter",
    "loby.Reset": "Restaurer",
    "footer.terms": "Termes et Conditions",
    "footer.privacy": "Avis de confidentialité",
    "footer.blog": "Blog",
    "footer.contact": "Contact",
    "footer.survey": "Enquête",
    "footer.tutorials": "Tutoriels",
    "footer.prices": "Prix",
    "footer.promoters": "Promoteurs",
    "header.signout": "Se déconnecter",
    "header.portal": "Mon Portail",
    "header.searchbar": "Barre de Recherche",
    "header.signin": "S'identifier",
    "header.country": "Pays",
    "header.nightmode": "Nocturne",
    "header.filters": "Filtres",
    "header.tellme": "Dis moi",
    "header.liked": "Favoris",
    "header.stickys": "Stickys",
    "header.properties": "Immobiliers",
    "header.services": "Services",
    "header.changeLangCntry": "Appliquer",
    "adscards.contact": "Contact",
    "repopup.usrank": "Mon évaluation",
    "repopup.reqinfo": "Demander des informations",
    "repopup.routemap": "Entrer une destination/adresse et voir les horaires et distances de ce ",
    "repopup.placesmap": "Choisissez le type de lieux",
    "repopup.new": "Nouveau",
    "mktfilters.portalkind": "Portail",
    "mktfilters.clients": "Clients",
    "mktfilters.brokers": "Couloirs",
    "mktfilters.developments": "Développements immobiliers",
    "mktfilters.country": "Pays",
    "mktfilters.prst": "État",
    "mktfilters.oper": "Opération",
    "mktfilters.rent": "Louer",
    "mktfilters.sell": "Vente",
    "mktfilters.contract": "Embauche",
    "mktfilters.property": "Propriété",
    "mktfilters.house": "Maison",
    "mktfilters.apartment": "Département",
    "mktfilters.land": "Terrain",
    "mktfilters.development": "Développement",
    "mktfilters.hollyday": "Vacances",
    "mktfilters.events": "Pour événements",
    "mktfilters.office": "Bureau",
    "mktfilters.commerce": "Local",
    "mktfilters.storage": "Magasin",
    "mktfilters.others": "Autres",
    "mktfilters.auctons": "Tentatives de but",
    "mktfilters.include": "Inclure",
    "mktfilters.exclude": "Exclure",
    "mktfilters.only": "Uniquement",
    "mktfilters.order": "Ordonner",
    "mktfilters.usrank": "Mon évaluation",
    "mktfilters.cheapest": "Prix ​​inférieur",
    "mktfilters.expensive": "Prix ​​plus élevé",
    "mktfilters.filter": "Filtre",
    "mktfilters.bedrooms": "Chambres",
    "mktfilters.bathrooms": "Toilettes",
    "mktfilters.parks": "Parkings",
    "mktfilters.min": "$Min",
    "mktfilters.max": "$Max",
    "mktfilters.zone": "Del./Mun./Mai.",
    "mktfilters.col": "Colonie",
    "mktfilters.residence": "Résidentiel",
    "mktfilters.enjoy": "Plaisir",
    "mktfilters.commercial": "Commercial",
    "mktfilters.more": "Plus",
    "mktfilters.alertme": "Créer Alerte",
    "adrestatecard.ConceptImgPack": "Espaces images",
    "adrestatecard.DescrImgPack": "Le coût mensuel de chaque espace image supplémentaire dépend du modèle de paiement publicitaire.",
    "adrestatecard.ConceptProdRelevAd": "Surbrillance l'annonce",
    "adrestatecard.DescrRelevAd": "En mettant en avant des annonces vous augmentez votre notoriété en tant que Partenaire et améliorez le positionnement de toutes vos publications simultanément, bénéficiant principalement à cette publication.",
    "adrestatecard.PPEventDescrREAd": "Lorsqu'un utilisateur demande à être contacté, le solde correspondant aux points de transaction sera déduit pour leur déblocage.",
    "adrestatecard.PPUseDescrREAd": "A chaque affichage de votre annonce, visite, mise en favori ou contact, les points seront déduits pour la transaction correspondante.",
    "adrestatecard.UseMemberSpaceDescrREAd": "Occuper avec cette publication l'un des espaces disponibles de l'Adhésion?",
    "adrestatecard.myREStep": "Publication de propriétés immobilières",
    "adrestatecard.myREStepAdv": "Publication de la propriété avec ID : {CardID}",
    "adrestatecard.success": "Publication réussie d'un bien immobilier avec ID : {CardID}",
    "adrestatecard.error": "La publication a échoué. {error}",
    "adrestatecard.myREStepPPEvent": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adrestatecard.myREStepPPUse": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adrestatecard.myREStepPREPay": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adrestatecard.myREStepPromise": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adrestatecard.myREStepMembership": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adrestatecard.InvalidFileLogo": " Rejeté. Les formats valides pour les images sont : png, jpg, jpeg, gif, webp",
    "adrestatecard.InvalidFilePreview": " Rejeté. Les formats valides pour les images sont : png, jpg, jpeg, gif, webp",
    "adrestatecard.msjgoodpractices": "Ajustez vos descriptions pour pouvoir publier dans le modèle 'Pay Per Event' puisque votre publication contient {SocialMed} {Numbers} dans la description et vous ne pouvez ajouter que {AcceptedNum} chiffres. Réajustez vos descriptions et évitez de répéter des données déjà ajoutées aux caractéristiques du bien comme les places de parking, etc... ou vous pouvez choisir un autre modèle de paiement sans cette restriction.",
    "adrestatecard.titlegoodpractices": "Vérification des bonnes pratiques",
    "adrestatecard.tutgoodpractitle": "Éviter les données de contact",
    "adrestatecard.signnewad": "Signer les termes et conditions",
    "adrestatecard.signnewdescr": "Mot de passe d'acceptation des conditions générales invalide",
    "adrestatecard.sucovrpct": "Téléchargement réussi avec {cargadas} images chargées à partir des {previsualizadas} publiées en raison d'une duplication ou d'un surdimensionnement. Les frais applicables ne tiennent compte que des images téléchargées. Nous vous enverrons le détail de votre annonce par e-mail une fois que sa conformité aux bonnes pratiques aura été vérifiée avant sa publication.",
    "adrestatecard.sucovrpctppevent": "Téléchargement réussi. Nous vous enverrons un email détaillé une fois le respect des bonnes pratiques vérifié avant publication.",
    "adrestatecard.sucovrpctppuse": "Téléchargement réussi. Nous vous enverrons un e-mail détaillé. N'oubliez pas d'avoir des points disponibles dans votre solde avant sa publication et pour les frais applicables ultérieurs.",
    "adrestatecard.sucovrpctmembersh": "Téléchargement réussi. Nous vous enverrons un e-mail détaillé pour que votre publication reste défilante.",
    "adrestatecard.adconcluded": "Annonce conclue",
    "adrestatecard.pmtmodbenef": "Mon modèle de paiement et mes avantages",
    "adrestatecard.titlogo": "Votre logotype immobilier (facultatif). Non visible dans le modèle 'Pay per Event'",
    "adrestatecard.logo": "Attachez votre logo à cette annonce.",
    "adrestatecard.freeimg1": "{imgratis} Espace(s) d'images gratuites.",
    "adrestatecard.freeimg2": " Photographies: (Gratuit) {imgratis}, (Payant) {imgpago}.",
    "adrestatecard.paymentimages": "Plus d'espaces pour plus d'Images de paiement.",
    "adrestatecard.HighlitedAd": "Après sélectionnée!",
    "adrestatecard.Higlight": "¡Mettre en évidence l'annonce et améliorer la réputation!",
    "adrestatecard.Proptype": "Type de propriété",
    "adrestatecard.Residential": "Résidentiel",
    "adrestatecard.HOME": "Maison",
    "adrestatecard.APARTMENT": "Département",
    "adrestatecard.DEVELOPMENT": "Développement de l'état réel",
    "adrestatecard.PRESELL": "Prévente",
    "adrestatecard.LAND": "Terre",
    "adrestatecard.ROOM": "Chambre",
    "adrestatecard.PROJECT": "Projet architectural",
    "adrestatecard.Rest": "Vacances",
    "adrestatecard.RESTHOME": "Maison",
    "adrestatecard.RESTAPARTMENT": "Département",
    "adrestatecard.RESTROOM": "Chambre",
    "adrestatecard.RESTOTHER": "Autre",
    "adrestatecard.Events": "Événements sociaux",
    "adrestatecard.EVENTGARDEN": "Jardins",
    "adrestatecard.EVENTROOM": "salon de fête",
    "adrestatecard.EVENTENCLOSURE": "Enceinte",
    "adrestatecard.EVENTOTHER": "Autres",
    "adrestatecard.Commerce": "Comercial",
    "adrestatecard.COMLOCAL": "Local",
    "adrestatecard.COMCONSULTING": "Cabinet médical",
    "adrestatecard.COMVIRTUALOFFICE": "Bureau virtuel",
    "adrestatecard.COMOFFICE": "Bureau",
    "adrestatecard.COMBUILDING": "Bâtiments",
    "adrestatecard.COMFLOOR": "étages",
    "adrestatecard.COMSTORAGE": "Magasin",
    "adrestatecard.COMSTATION": "Comptoir commercial",
    "adrestatecard.COMOTHERCOMERCE": "Autre",
    "adrestatecard.Industry": "Industriel",
    "adrestatecard.INDWHAREHOUSE": "Navire industrielle",
    "adrestatecard.INDSTORAGE": "Magasin",
    "adrestatecard.INDLAND": "Terre",
    "adrestatecard.INDOTHER": "Autre",
    "adrestatecard.Transtype": "Type de transaction",
    "adrestatecard.selltrans": "Vente",
    "adrestatecard.renttrans": "Louer",
    "adrestatecard.passtrans": "Remettre",
    "adrestatecard.Transprice": "Prix",
    "adrestatecard.Transaddexp": "Coûts additionnels?",
    "adrestatecard.NO": "Ne",
    "adrestatecard.MANTENANCE": "Maintenance",
    "adrestatecard.GUARANTEE": "Politique juridique",
    "adrestatecard.DEPOSIT": "Services d'entiercement",
    "adrestatecard.RESERVED": "écartelé",
    "adrestatecard.MULTIPLE": "Plusieurs",
    "adrestatecard.OTHERS": "Autres",
    "adrestatecard.addexpammt": "Montant des dépenses supplémentaires",
    "adrestatecard.auction": "C'est une enchère bancaire?",
    "adrestatecard.feeammount": "Montant ou pourcentage de la commission",
    "adrestatecard.m2c": "Mètres construits",
    "adrestatecard.m2t": "Mètres terrestres",
    "adrestatecard.m2g": "Compteurs de jardin",
    "adrestatecard.bedrooms": "Recamarás / Bureaux / etc.",
    "adrestatecard.bathrooms": "Sanitaire",
    "adrestatecard.parks": "Places de parking",
    "adrestatecard.pets": "les animaux sont admis?",
    "adrestatecard.usrkind": "¿Quel type d'utilisateur êtes vous?",
    "adrestatecard.OWNER": "Propriétaire",
    "adrestatecard.BROKER": "Agent immobilier",
    "adrestatecard.sharefee": "¿Vous accordez ou partagez une commission?",
    "adrestatecard.FEENOT": "Ne",
    "adrestatecard.FEEAMMOUNT": "Commission monétaire $",
    "adrestatecard.FEEPERCENTAGE": "Commission en pourcentage %",
    "adrestatecard.PETLIMITED": "Limité",
    "adrestatecard.PETCONDITIONS": "Conditionné",
    "adrestatecard.URLvideo": "Lien vidéo de la propriété (URL)",
    "adrestatecard.description": "Description de la propriété (Évitez les coordonnées dans les publications Pay-Per-Event)",
    "adrestatecard.condition": "Conditions spéciales (Évitez les coordonnées dans les publications Pay-Per-Event)",
    "adrestatecard.relevant": "Aspects pertinents (Évitez les coordonnées dans les publications Pay-Per-Event)",
    "adrestatecard.pptyaddrs": "Capture d'adresse et confirmation",
    "adrestatecard.prst": "État / Province",
    "adrestatecard.zone": "Délégation / Commune / Mairie / ...",
    "adrestatecard.col": "colonies",
    "adrestatecard.street": "rue",
    "adrestatecard.enum": "Numéro extérieur et intérieur",
    "adrestatecard.zipcode": "Code postal",
    "adrestatecard.latlong": "Latitude et longitude de google maps",
    "adrestatecard.gearth": "Lien Google Earth",
    "adrestatecard.rates": " Tarifs actuels pour les publications en {Cntry}",
    "adrestatecard.buypointsequiv": "Acquérir des points (1Pt = {PricePerPoint})",
    "adrestatecard.pmmtmodchosen": "Choisissez le modèle de paiement que vous préférez pour cette annonce",
    "adrestatecard.ppe1": "Payer par événement",
    "adrestatecard.ppe2": "Gratuit jusqu'au moment du contact {PPECntcPrice}.",
    "adrestatecard.ppu1": "Payer pour utilisation",
    "adrestatecard.ppu2": "De {PPUDispPrice} Cents à {PPUCntcPrice} pour chaque action et avec un bonus pour commencer sans dépenser.",
    "adrestatecard.memb1": "Utilisation de l'adhésion",
    "adrestatecard.memb2": "(Vos espaces pré-contractés disponibles)",
    "adrestatecard.membprep1": "Adhésions",
    "adrestatecard.membprep2": "Prépayé",
    "adrestatecard.membprep3": "Descuentos hasta del {MaxPrcDiscount} ( {MaxAmtDiscount} )",
    "adrestatecard.membprom1": "Adhésions",
    "adrestatecard.membprom2": "Promesse de paiement",
    "adrestatecard.membprom3": "Niveau 1 à 3 de 2 à 12 mois avec remises, avantages et mensualité.",
    "adrestatecard.inputpassword": "Tapez votre mot de passe",
    "adrestatecard.terms2": "Termes et conditions",
    "adrestatecard.termsaccept": "Acceptation des conditions actuelles de publication",
    "adrestatecard.sendtocheck": "Soumettre le message pour vérification",
    "adrestatecard.sendtopublish": "Soumettre le message",
    "adrestatecard.buypoints": "Acquisition de points",
    "adzsecard.ConceptImgPack": "Espaces images",
    "adzsecard.DescrImgPack": "Le coût mensuel de chaque espace image supplémentaire dépend du modèle de paiement publicitaire.",
    "adzsecard.ConceptProdRelevAd": "Surbrillance l'annonce",
    "adzsecard.DescrRelevAd": "En mettant en avant des annonces vous augmentez votre notoriété en tant que Partenaire et améliorez le positionnement de toutes vos publications simultanément, bénéficiant principalement à cette publication.",
    "adzsecard.PPUseDescrREAd": "A chaque affichage de votre annonce, visite, mise en favori ou contact, les points seront déduits pour la transaction correspondante.",
    "adzsecard.UseMemberSpaceDescrREAd": "Occuper avec cette publication l'un des espaces disponibles de l'Adhésion?",
    "adzsecard.myZSEStep": "Promotion d'un établissement ou d'un service",
    "adzsecard.myZSEStepAdv": "Promotion d'un établissement ou d'un service avec pièce d'identité : {CardID}",
    "adzsecard.success": "Publication réussie de l'établissement ou du service avec ID : {CardID}",
    "adzsecard.error": "La publication a échoué. {error}",
    "adzsecard.myREStepPPUse": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adzsecard.myREStepPREPay": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adzsecard.myREStepPromise": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adzsecard.myREStepMembership": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adzsecard.InvalidFileLogo": " Rejeté. Les formats valides pour les images sont : png, jpg, jpeg, gif, webp",
    "adzsecard.InvalidFilePreview": " Rejeté. Les formats valides pour les images sont : png, jpg, jpeg, gif, webp",
    "adzsecard.signnewad": "Signer les termes et conditions",
    "adzsecard.signnewdescr": "Mot de passe d'acceptation des conditions générales invalide",
    "adzsecard.sucovrpct": "Téléchargement réussi avec {cargadas} images chargées à partir des {previsualizadas} publiées en raison d'une duplication ou d'un surdimensionnement. Les frais applicables ne tiennent compte que des images téléchargées. Nous vous enverrons le détail de votre annonce par e-mail une fois que sa conformité aux bonnes pratiques aura été vérifiée avant sa publication.",
    "adzsecard.sucovrpctppuse": "Téléchargement réussi. Nous vous enverrons un e-mail détaillé. N'oubliez pas d'avoir des points disponibles dans votre solde avant sa publication et pour les frais applicables ultérieurs.",
    "adzsecard.sucovrpctmembersh": "Téléchargement réussi. Nous vous enverrons un e-mail détaillé pour que votre publication reste défilante.",
    "adzsecard.adconcluded": "Annonce conclue",
    "adzsecard.pmtmodbenef": "Mon modèle de paiement et mes avantages",
    "adzsecard.titlogo": "Logo de votre établissement ou service (facultatif). Non visible dans le modèle 'Pay per Event'",
    "adzsecard.logo": "Attachez votre logo à cette annonce.",
    "adzsecard.freeimg1": "{imgratis} Espace(s) d'images gratuites.",
    "adzsecard.freeimg2": " Photographies: (Gratuit) {imgratis}, (Payant) {imgpago}.",
    "adzsecard.paymentimages": "Plus d'espaces pour plus d'Images de paiement.",
    "adzsecard.HighlitedAd": "Après sélectionnée!",
    "adzsecard.Higlight": "¡Mettre en évidence l'annonce et améliorer la réputation!",
    "adzsecard.description": "Description de votre service ou établissement (Évitez les coordonnées dans les publications Pay-Per-Event)",
    "adzsecard.pptyaddrs": "Capturez et confirmez l'adresse (facultatif)",
    "adzsecard.prst": "État / Province",
    "adzsecard.zone": "Délégation / Commune / Mairie / ...",
    "adzsecard.col": "colonies",
    "adzsecard.street": "rue",
    "adzsecard.enum": "Numéro extérieur et intérieur",
    "adzsecard.zipcode": "Code postal",
    "adzsecard.latlong": "Latitude et longitude de google maps",
    "adzsecard.gearth": "Lien Google Earth",
    "adzsecard.rates": " Tarifs actuels pour les publications en {Cntry}",
    "adzsecard.buypointsequiv": "Acquérir des points (1Pt = {PricePerPoint})",
    "adzsecard.pmmtmodchosen": "Choisissez le modèle de paiement que vous préférez pour cette annonce",
    "adzsecard.ppu1": "Payer pour utilisation",
    "adzsecard.ppu2": "De {PPUDispPrice} Cents à {PPUCntcPrice} pour chaque action et avec un bonus pour commencer sans dépenser.",
    "adzsecard.memb1": "Utilisation de l'adhésion",
    "adzsecard.memb2": "(Vos espaces pré-contractés disponibles)",
    "adzsecard.membprep1": "Adhésions",
    "adzsecard.membprep2": "Prépayé",
    "adzsecard.membprep3": "Descuentos hasta del {MaxPrcDiscount} ( {MaxAmtDiscount} )",
    "adzsecard.membprom1": "Adhésions",
    "adzsecard.membprom2": "Promesse de paiement",
    "adzsecard.membprom3": "Niveau 1 à 3 de 2 à 12 mois avec remises, avantages et mensualité.",
    "adzsecard.inputpassword": "Tapez votre mot de passe",
    "adzsecard.terms2": "Termes et conditions",
    "adzsecard.termsaccept": "Acceptation des conditions actuelles de publication",
    "adzsecard.sendtocheck": "Soumettre le message pour vérification",
    "adzsecard.sendtopublish": "Soumettre le message",
    "adzsecard.buypoints": "Acquisition de points",
    "adzsecard.promestablishment": "Promouvoir établissement",
    "adzsecard.promservice": "Offrir un service",
    "adzsecard.category": "Catégorie",
    "adzsecard.HOMEMANTENANCE": "Maintenance (Plombier, Electricien, Fumigation...)",
    "adzsecard.HOMESERVICES": "Services (Gaz, Jardin, Baignoire/Promenade pour animaux, Ménage...)",
    "adzsecard.HOMEOTHER": "Autres",
    "adzsecard.ARTHOME": "Pour la maison",
    "adzsecard.ARTCAR": "Automobile",
    "adzsecard.ARTOFF": "Au bureau",
    "adzsecard.ARTPERS": "Personnel",
    "adzsecard.ARTDRESS": "Vêtements",
    "adzsecard.ARTPET": "Pour animaux de compagnie",
    "adzsecard.ARTSCHO": "Académiques",
    "adzsecard.ARTOTHER": "Divers",
    "adzsecard.HEALTHMEDICINE": "Docteur",
    "adzsecard.HEALTHMENTAL": "Holistique",
    "adzsecard.HEALTHSPORT": "Sports et disciplines",
    "adzsecard.HEALTHFOOD": "Nutritionnelle",
    "adzsecard.HEALTHESTATIC": "Esthétique",
    "adzsecard.HEALTHPET": "Animal",
    "adzsecard.HEALTHOTHER": "Divers",
    "adzsecard.ACADEMICSCHOOL": "Écoliers",
    "adzsecard.ACADEMICHELP": "Régularisation",
    "adzsecard.ACADEMICEXTRA": "Périscolaire",
    "adzsecard.ACADEMICSPORTS": "Sports et disciplines",
    "adzsecard.ACADEMICSPRING": "Ateliers",
    "adzsecard.ACADEMICARTS": "Arts",
    "adzsecard.ACADEMICOTHERS": "Autres",
    "adzsecard.PROFESIONALSHEALTH": "De la santé",
    "adzsecard.PROFESIONALSPSYCHOLOGY": "Psychologique",
    "adzsecard.PROFESIONALSLEGAL": "Légal",
    "adzsecard.PROFESIONALSFINANCIAL": "Secteur financier",
    "adzsecard.PROFESIONALSCONSULTANT": "Conseillers",
    "adzsecard.PROFESIONALSOTHERS": "Autres",
    "adzsecard.ENTDIGITAL": "Digital",
    "adzsecard.ENTMUSICAL": "Musical",
    "adzsecard.ENTVISUAL": "Visuel",
    "adzsecard.ENTSPORT": "Sportif",
    "adzsecard.ENTSHOW": "Spectacles",
    "adzsecard.ENTFAMILY": "Famille",
    "adzsecard.ENTCULTURE": "Culturel",
    "adzsecard.ENTSOCIAL": "Coexistence sociale",
    "adzsecard.ENTOTHERS": "Autres",
    "adzsecard.CARMANTENANCE": "Maintenance",
    "adzsecard.CARCOMMERCE": "Commerce",
    "adzsecard.CAROTHERS": "Autres",
    "adzsecard.OTHERS": "Divers",
    "adzsecard.home": "Foyer",
    "adzsecard.articles": "Articles",
    "adzsecard.health": "Santé et bien-être",
    "adzsecard.academics": "Académique",
    "adzsecard.professional": "Professionnels",
    "adzsecard.entretainment": "Divertissement",
    "adzsecard.auto": "Automobile",
    "adzsecard.others": "Autres",
    "adzsecard.brand": "Nom commercial ou marque",
    "adzsecard.keywords": "Mots-clés de recherche : (Sushi, Plombier, Gaz, Papeterie, Menuisier, Bureau, etc.)",
    "adzsecard.slogan": "Slogan",
    "adzsecard.homeservice": "Proposez-vous un service à domicile ?",
    "adzsecard.website": "Page d'Internet",
    "adzsecard.email": "Courrier électronique",
    "adzsecard.tel1": "Téléphone 1",
    "adzsecard.tel2": "Téléphone 2",
    "adzsecard.tel3": "Téléphone 3",
    "adzsecard.whatsapp": "WhatsApp",
    "adzsecard.wechat": "WeChat",
    "adzsecard.facebook": "facebook",
    "adzsecard.instagram": "Instagram",
    "adzsecard.twiter": "Twiter",
    "adzsecard.youtube": "Youtube",
    "adzsecard.appstore": "Lien vers votre AppStore IOs",
    "adzsecard.playstore": "Lien vers votre boutique Google Play",
    "adzsecard.color": "Couleur de fond de votre annonce",
    "adzsecard.videourl": "Lien vidéo (URL) de votre établissement ou service",
    "adzsecard.promotions": "Promotions",
    "adzsecard.calltoact": "Inviter à l'action",
    "adzsecard.branches": "Succursales",
    "adzsecard.schedule": "Horaires d'ouverture",
    "adzsecard.day1": "Lundi",
    "adzsecard.day2": "Mardi",
    "adzsecard.day3": "Mercredi",
    "adzsecard.day4": "Jeudi",
    "adzsecard.day5": "Vendredi",
    "adzsecard.day6": "Samedi",
    "adzsecard.day7": "Dimanche",
    "adzsecard.from": "De: ",
    "adzsecard.to": "à: ",
    "adzsecard.important": "IMPORTANT:",
    "adzsecard.zonestopublish": "Dans quels domaines publierez-vous votre annonce ? ({zonas} messages)",
    "adzsecard.advise": "Chaque Zone compte pour 1 annonce supplémentaire sur votre relevé de compte",
    "adzsecard.autocompletezones": "Écrivez ici les zones où vous publierez votre annonce",
    "adzsecard.typecharpublish": "Choisissez le type et les caractéristiques de votre Publication.",
    "adzsecard.frontcard": "Carte avant ({PtsReq} pts)",
    "adzsecard.backcard": "Carte recto et verso ({PtsReq} pts)",
    "adzsecard.fullcard": "Carte avant et plein écran ({PtsReq} pts)",
    "adzsecard.addoptfrontcard": "Options de carte avant supplémentaires",
    "adzsecard.titlogocard": "Ajoutez votre logo",
    "adzsecard.logocard": "Logo ( {PtsReq} pts)",
    "adzsecard.tithomeservicecard": "Activer l'icône du service à domicile",
    "adzsecard.homeservicecard": "Service à domicile ({PtsReq} pts)",
    "adzsecard.titactivenotificationcard": "Notifier vos Promotions à tout utilisateur du portail de Services",
    "adzsecard.activenotificationcard": "Notification active ({PtsReq} pts)",
    "adzsecard.titpassivenotificationcard": "Signalez vos promotions à celui qui vous marque avec Sticky",
    "adzsecard.passivenotificationcard": "Notifications passives ({PtsReq} pts)",
    "adzsecard.titsharebymailwhatscard": "Permettre qu'ils puissent vous partager par Mail et WhatsApp",
    "adzsecard.sharebymailwhatscard": "Partager par messagerie ({PtsReq} pts)",
    "adzsecard.titchatfollowcard": "Recevoir des demandes de devis ou des doutes depuis le portail",
    "adzsecard.chatfollowcard": "Contact écrit ({PtsReq} pts)",
    "adzsecard.titsmsnotifcard": "Recevez des notifications par SMS lorsqu'un client demande des informations",
    "adzsecard.smsnotifcard": "SMS actif ({PtsReq} pts)",
    "adzsecard.titmyzoneblogcard": "Apparaît sur les cartes dynamiques sur l'écran principal des services",
    "adzsecard.myzoneblogcard": "Signes dans le portail de service ({PtsReq} pts)",
    "adzsecard.titpublicblogcard": "Apparaît dans les cartes dynamiques sur le blog du portail",
    "adzsecard.publicblogcard": "Libellés dans le blog ({PtsReq} pts)",
    "adzsecard.addoptbackcard": "Options de dos de carte supplémentaires",
    "adzsecard.titschedulecard": "Déclarez vos heures d'ouverture",
    "adzsecard.schedulecard": "Heures ({PtsReq} pts)",
    "adzsecard.titshowsocialmedcard": "Activer les icônes qui se connectent à vos réseaux sociaux",
    "adzsecard.showsocialmedcard": "Afficher les réseaux sociaux ({PtsReq} pts)",
    "adzsecard.titpricelistcard": "Ajoutez votre liste de prix",
    "adzsecard.pricelistcard": "Liste de prix ({PtsReq} pts)",
    "adzsecard.titproductscard": "Ajouter un catalogue de 7 produits avec description et/ou prix",
    "adzsecard.productscard": "Catalogue de produits ({PtsReq} pts)",
    "adzsecard.titdescriptionscard": "Décrivez vos produits",
    "adzsecard.descriptionscard": "Descriptions ({PtsReq} pts)",
    "adzsecard.titcalltoactcard": "Invitez vos parties intéressées à agir",
    "adzsecard.calltoactcard": "Appel à l'action ({PtsReq} pts)",
    "adzsecard.titgoogleappstorescard": "IOs App Store et/ou Google Playstore",
    "adzsecard.googleappstorescard": "Magasins numériques ({PtsReq} pts)",
    "adzsecard.addoptfullcard": "Options supplémentaires pour le plein écran",
    "adzsecard.titgeolocatecard": "Apparaît sur les cartes du portail",
    "adzsecard.geolocatecard": "Géolocalisation ({PtsReq} pts)",
    "adzsecard.titbranchesmapcard": "Ajouter un lien hypertexte à votre carte de succursale",
    "adzsecard.branchesmapcard": "Carte de branche ({PtsReq} pts)",
    "adzsecard.titvideocard": "Ajoutez des vidéos à votre annonce depuis notre chaîne youtube",
    "adzsecard.videocard": "Vidéos de NIXIN Channel ({PtsReq} pts)",
    "adzsecard.titqucodecard": "Ajouter un code QR",
    "adzsecard.qucodecard": "Code QR ({PtsReq} pts)",
    "adncacard.ConceptImgPack": "Espaces images",
    "adncacard.DescrImgPack": "Le coût mensuel de chaque espace image supplémentaire dépend du modèle de paiement publicitaire.",
    "adncacard.ConceptProdRelevAd": "Surbrillance l'annonce",
    "adncacard.DescrRelevAd": "En mettant en avant des annonces vous augmentez votre notoriété en tant que Partenaire et améliorez le positionnement de toutes vos publications simultanément, bénéficiant principalement à cette publication.",
    "adncacard.PPUseDescrREAd": "A chaque affichage de votre annonce, visite, mise en favori ou contact, les points seront déduits pour la transaction correspondante.",
    "adncacard.UseMemberSpaceDescrREAd": "Occuper avec cette publication l'un des espaces disponibles de l'Adhésion?",
    "adncacard.myNCAStep": "Publication adressée aux Annonceurs NIXIN",
    "adncacard.myNCAStepAdv": "Identifiant de publication de l'annonceur NIXIN : {CardID}",
    "adncacard.success": "Publication réussie pour les annonceurs NIXIN avec ID : {CardID}",
    "adncacard.error": "La publication a échoué. {error}",
    "adncacard.myNCAStepPPUse": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adncacard.myNCAStepPREPay": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adncacard.myNCAStepPromise": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adncacard.myNCAStepMembership": "Signez avec votre mot de passe l'Acceptation des conditions générales de sa vérification et de sa Publication",
    "adncacard.InvalidFileLogo": " Rejeté. Les formats valides pour les images sont : png, jpg, jpeg, gif, webp",
    "adncacard.InvalidFilePreview": " Rejeté. Les formats valides pour les images sont : png, jpg, jpeg, gif, webp",
    "adncacard.signnewad": "Signer les termes et conditions",
    "adncacard.signnewdescr": "Mot de passe d'acceptation des conditions générales invalide",
    "adncacard.sucovrpct": "Téléchargement réussi avec {cargadas} images chargées à partir des {previsualizadas} publiées en raison d'une duplication ou d'un surdimensionnement. Les frais applicables ne tiennent compte que des images téléchargées. Nous vous enverrons le détail de votre annonce par e-mail une fois que sa conformité aux bonnes pratiques aura été vérifiée avant sa publication.",
    "adncacard.sucovrpctppuse": "Téléchargement réussi. Nous vous enverrons un e-mail détaillé. N'oubliez pas d'avoir des points disponibles dans votre solde avant sa publication et pour les frais applicables ultérieurs.",
    "adncacard.sucovrpctmembersh": "Téléchargement réussi. Nous vous enverrons un e-mail détaillé pour que votre publication reste défilante.",
    "adncacard.adconcluded": "Annonce conclue",
    "adncacard.pmtmodbenef": "Mon modèle de paiement et mes avantages",
    "adncacard.titlogo": "Logo de votre établissement ou service (facultatif). Non visible dans le modèle 'Pay per Event'",
    "adncacard.logo": "Attachez votre logo à cette annonce.",
    "adncacard.freeimg1": "{imgratis} Espace(s) d'images gratuites.",
    "adncacard.freeimg2": " Photographies: (Gratuit) {imgratis}, (Payant) {imgpago}.",
    "adncacard.paymentimages": "Plus d'espaces pour plus d'Images de paiement.",
    "adncacard.HighlitedAd": "Après sélectionnée!",
    "adncacard.Higlight": "¡Mettre en évidence l'annonce et améliorer la réputation!",
    "adncacard.description": "Description de votre établissement ou service (Évitez les coordonnées dans les publications Pay-Per-Event)",
    "adncacard.pptyaddrs": "Capturez et confirmez l'adresse (facultatif)",
    "adncacard.prst": "État / Province",
    "adncacard.zone": "Délégation / Commune / Mairie / ...",
    "adncacard.col": "colonies",
    "adncacard.street": "rue",
    "adncacard.enum": "Numéro extérieur et intérieur",
    "adncacard.zipcode": "Code postal",
    "adncacard.latlong": "Latitude et longitude de google maps",
    "adncacard.gearth": "Lien Google Earth",
    "adncacard.rates": " Tarifs actuels pour les publications en {Cntry}",
    "adncacard.buypointsequiv": "Acquérir des points (1Pt = {PricePerPoint})",
    "adncacard.pmmtmodchosen": "Choisissez le modèle de paiement que vous préférez pour cette annonce",
    "adncacard.ppu1": "Payer pour utilisation",
    "adncacard.ppu2": "De {PPUDispPrice} Cents à {PPUCntcPrice} pour chaque action et avec un bonus pour commencer sans dépenser.",
    "adncacard.memb1": "Utilisation de l'adhésion",
    "adncacard.memb2": "(Vos espaces pré-contractés disponibles)",
    "adncacard.membprep1": "Adhésions",
    "adncacard.membprep2": "Prépayé",
    "adncacard.membprep3": "Descuentos hasta del {MaxPrcDiscount} ( {MaxAmtDiscount} )",
    "adncacard.membprom1": "Adhésions",
    "adncacard.membprom2": "Promesse de paiement",
    "adncacard.membprom3": "Niveau 1 à 3 de 2 à 12 mois avec remises, avantages et mensualité.",
    "adncacard.inputpassword": "Tapez votre mot de passe",
    "adncacard.terms2": "Termes et conditions",
    "adncacard.termsaccept": "Acceptation des conditions actuelles de publication",
    "adncacard.sendtocheck": "Soumettre le message pour vérification",
    "adncacard.sendtopublish": "Soumettre le message",
    "adncacard.buypoints": "Acquisition de points",
    "adncacard.promestablishment": "Promouvoir établissement",
    "adncacard.promservice": "Offrir un service",
    "adncacard.category": "Catégorie",
    "adncacard.HOMEMANTENANCE": "Maintenance (Plombier, Electricien, Fumigation...)",
    "adncacard.HOMESERVICES": "Services (Gaz, Jardin, Baignoire/Promenade pour animaux, Ménage...)",
    "adncacard.HOMEOTHER": "Autres",
    "adncacard.ARTHOME": "Pour la maison",
    "adncacard.ARTCAR": "Automobile",
    "adncacard.ARTOFF": "Au bureau",
    "adncacard.ARTPERS": "Personnel",
    "adncacard.ARTDRESS": "Vêtements",
    "adncacard.ARTPET": "Pour animaux de compagnie",
    "adncacard.ARTSCHO": "Académiques",
    "adncacard.ARTOTHER": "Divers",
    "adncacard.HEALTHMEDICINE": "Docteur",
    "adncacard.HEALTHMENTAL": "Holistique",
    "adncacard.HEALTHSPORT": "Sports et disciplines",
    "adncacard.HEALTHFOOD": "Nutritionnelle",
    "adncacard.HEALTHESTATIC": "Esthétique",
    "adncacard.HEALTHPET": "Animal",
    "adncacard.HEALTHOTHER": "Divers",
    "adncacard.ACADEMICSCHOOL": "Écoliers",
    "adncacard.ACADEMICHELP": "Régularisation",
    "adncacard.ACADEMICEXTRA": "Périscolaire",
    "adncacard.ACADEMICSPORTS": "Sports et disciplines",
    "adncacard.ACADEMICSPRING": "Ateliers",
    "adncacard.ACADEMICARTS": "Arts",
    "adncacard.ACADEMICOTHERS": "Autres",
    "adncacard.PROFESIONALSHEALTH": "De la santé",
    "adncacard.PROFESIONALSPSYCHOLOGY": "Psychologique",
    "adncacard.PROFESIONALSLEGAL": "Légal",
    "adncacard.PROFESIONALSFINANCIAL": "Secteur financier",
    "adncacard.PROFESIONALSCONSULTANT": "Conseillers",
    "adncacard.PROFESIONALSOTHERS": "Autres",
    "adncacard.ENTDIGITAL": "Digital",
    "adncacard.ENTMUSICAL": "Musical",
    "adncacard.ENTVISUAL": "Visuel",
    "adncacard.ENTSPORT": "Sportif",
    "adncacard.ENTSHOW": "Spectacles",
    "adncacard.ENTFAMILY": "Famille",
    "adncacard.ENTCULTURE": "Culturel",
    "adncacard.ENTSOCIAL": "Coexistence sociale",
    "adncacard.ENTOTHERS": "Autres",
    "adncacard.CARMANTENANCE": "Maintenance",
    "adncacard.CARCOMMERCE": "Commerce",
    "adncacard.CAROTHERS": "Autres",
    "adncacard.OTHERS": "Divers",
    "adncacard.home": "Foyer",
    "adncacard.articles": "Articles",
    "adncacard.health": "Santé et bien-être",
    "adncacard.academics": "Académique",
    "adncacard.professional": "Professionnels",
    "adncacard.entretainment": "Divertissement",
    "adncacard.auto": "Automobile",
    "adncacard.others": "Autres",
    "adncacard.brand": "Nom commercial ou marque",
    "adncacard.keywords": "Mots-clés de recherche : (Sushi, Plombier, Gaz, Papeterie, Menuisier, Bureau, etc.)",
    "adncacard.slogan": "Slogan",
    "adncacard.homeservice": "Proposez-vous un service à domicile ?",
    "adncacard.website": "Page d'Internet",
    "adncacard.email": "Courrier électronique",
    "adncacard.tel1": "Téléphone 1",
    "adncacard.tel2": "Téléphone 2",
    "adncacard.tel3": "Téléphone 3",
    "adncacard.whatsapp": "WhatsApp",
    "adncacard.wechat": "WeChat",
    "adncacard.facebook": "facebook",
    "adncacard.instagram": "Instagram",
    "adncacard.twiter": "Twiter",
    "adncacard.youtube": "Youtube",
    "adncacard.appstore": "Lien vers votre AppStore IOs",
    "adncacard.playstore": "Lien vers votre boutique Google Play",
    "adncacard.color": "Couleur de fond de votre annonce",
    "adncacard.videourl": "Lien vidéo (URL) de l'établissement ou du service",
    "adncacard.promotions": "Promotions",
    "adncacard.calltoact": "Inviter à l'action",
    "adncacard.branches": "Succursales",
    "adncacard.schedule": "Horaires d'ouverture",
    "adncacard.day1": "Lundi",
    "adncacard.day2": "Mardi",
    "adncacard.day3": "Mercredi",
    "adncacard.day4": "Jeudi",
    "adncacard.day5": "Vendredi",
    "adncacard.day6": "Samedi",
    "adncacard.day7": "Dimanche",
    "adncacard.from": "De: ",
    "adncacard.to": "à: ",
    "adncacard.important": "IMPORTANT:",
    "adncacard.zonestopublish": "Dans quels domaines publierez-vous votre annonce ? ({zonas} messages)",
    "adncacard.advise": "Chaque Zone compte pour 1 annonce supplémentaire sur votre relevé de compte",
    "adncacard.autocompletezones": "Écrivez ici les zones où vous publierez votre annonce",
    "adncacard.typecharpublish": "Choisissez le type et les caractéristiques de votre Publication.",
    "adncacard.frontcard": "Carte avant ({PtsReq} pts)",
    "adncacard.backcard": "Carte recto et verso ({PtsReq} pts)",
    "adncacard.fullcard": "Carte avant et plein écran ({PtsReq} pts)",
    "adncacard.addoptfrontcard": "Options de carte avant supplémentaires",
    "adncacard.titlogocard": "Ajoutez votre logo",
    "adncacard.logocard": "Logo ( {PtsReq} pts)",
    "adncacard.tithomeservicecard": "Activer l'icône du service à domicile",
    "adncacard.homeservicecard": "Service à domicile ({PtsReq} pts)",
    "adncacard.titactivenotificationcard": "Notifier vos Promotions à tout utilisateur du portail de Services",
    "adncacard.activenotificationcard": "Notification active ({PtsReq} pts)",
    "adncacard.titpassivenotificationcard": "Signalez vos promotions à celui qui vous marque avec Sticky",
    "adncacard.passivenotificationcard": "Notifications passives ({PtsReq} pts)",
    "adncacard.titsharebymailwhatscard": "Permettre qu'ils puissent vous partager par Mail et WhatsApp",
    "adncacard.sharebymailwhatscard": "Partager par messagerie ({PtsReq} pts)",
    "adncacard.titchatfollowcard": "Recevoir des demandes de devis ou des doutes depuis le portail",
    "adncacard.chatfollowcard": "Contact écrit ({PtsReq} pts)",
    "adncacard.titsmsnotifcard": "Recevez des notifications par SMS lorsqu'un client demande des informations",
    "adncacard.smsnotifcard": "SMS actif ({PtsReq} pts)",
    "adncacard.titmyzoneblogcard": "Apparaît sur les cartes dynamiques sur l'écran principal des services",
    "adncacard.myzoneblogcard": "Signes dans le portail de service ({PtsReq} pts)",
    "adncacard.titpublicblogcard": "Apparaît dans les cartes dynamiques sur le blog du portail",
    "adncacard.publicblogcard": "Libellés dans le blog ({PtsReq} pts)",
    "adncacard.addoptbackcard": "Options de dos de carte supplémentaires",
    "adncacard.titschedulecard": "Déclarez vos heures d'ouverture",
    "adncacard.schedulecard": "Heures ({PtsReq} pts)",
    "adncacard.titshowsocialmedcard": "Activer les icônes qui se connectent à vos réseaux sociaux",
    "adncacard.showsocialmedcard": "Afficher les réseaux sociaux ({PtsReq} pts)",
    "adncacard.titpricelistcard": "Ajoutez votre liste de prix",
    "adncacard.pricelistcard": "Liste de prix ({PtsReq} pts)",
    "adncacard.titproductscard": "Ajouter un catalogue de 7 produits avec description et/ou prix",
    "adncacard.productscard": "Catalogue de produits ({PtsReq} pts)",
    "adncacard.titdescriptionscard": "Décrivez vos produits",
    "adncacard.descriptionscard": "Descriptions ({PtsReq} pts)",
    "adncacard.titcalltoactcard": "Invitez vos parties intéressées à agir",
    "adncacard.calltoactcard": "Appel à l'action ({PtsReq} pts)",
    "adncacard.titgoogleappstorescard": "IOs App Store et/ou Google Playstore",
    "adncacard.googleappstorescard": "Magasins numériques ({PtsReq} pts)",
    "adncacard.addoptfullcard": "Options supplémentaires pour le plein écran",
    "adncacard.titgeolocatecard": "Apparaît sur les cartes du portail",
    "adncacard.geolocatecard": "Géolocalisation ({PtsReq} pts)",
    "adncacard.titbranchesmapcard": "Ajouter un lien hypertexte à votre carte de succursale",
    "adncacard.branchesmapcard": "Carte de branche ({PtsReq} pts)",
    "adncacard.titvideocard": "Ajoutez des vidéos à votre annonce depuis notre chaîne youtube",
    "adncacard.videocard": "Vidéos de NIXIN Channel ({PtsReq} pts)",
    "adncacard.titqucodecard": "Ajouter un code QR",
    "adncacard.qucodecard": "Code QR ({PtsReq} pts)",
    "adtoblogcard.pubinblog": "Publier sur le blog NIXIN"
}